### ISSUE TITLE
Upload package on PyPI

### ISSUE THREAD

**Issue by FrancescoCasalegno** [titipata/pubmed_parser#101]
Hi, and thanks for this very nice package!

I would like to use your package for a project. However, if the package is not on `PyPI`, I cannot declare it as a dependency of my own package.

I see that you have done more than a release on GitHub, so uploading on PyPI should be easy.

Could you please do that? Thank you in advance!

**Comment by titipata** [comment]
Hi @FrancescoCasalegno,

Yes, I just uploaded Pubmed parser version 0.3.0 on PyPI here https://pypi.org/project/pubmed-parser/. Can you try installing the package using `pip install pubmed-parser` to see if it works for you? If it works, I can add the instruction on  `README.md`

Cheers,
Titipat A.

**Comment by FrancescoCasalegno** [comment]
It works perfectly, thanks!

**Comment by titipata** [comment]
@FrancescoCasalegno Awesome! I will close this issue for now since I updated README. Let me know if something crashes, I can reopen this issue!
