### ISSUE TITLE
PMC OA: tags in the <journal-title> field break parse_pubmed_xml

### ISSUE THREAD

**Issue by ghost** [titipata/pubmed_parser#110]
**Describe the bug**
Tags in the `<journal-title>` value cause:
```python-traceback
File ".../pubmed_oa_parser.py", line 153, in parse_pubmed_xml
    journal = " ".join([j.text for j in journal_node])
TypeError: sequence item 0: expected str instance, NoneType found
``` 
In the case of https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=7147450, changing 
```
<italic>In Vivo</italic> Models of Inflammation
```

to 
```
In Vivo Models of Inflammation
```
fixes it.

**To Reproduce**
```python
import pubmed_parser as pp
pp.parse_pubmed_xml('efetch_7147450.xml')
pp.parse_pubmed_xml('efetch_7147450_fixed.xml')
```

[xmls.zip](https://github.com/titipata/pubmed_parser/files/7810547/xmls.zip)

**Comment by titipata** [comment]
@aren-lorenson-enveda thanks for your issue. I guess a quick fix is to change to the following:

```py
journal = " ".join([j.text for j in journal_node if j is not None])
```

However, I will check if it works properly later on (or if you try and it works, feel free to make a pull request)!

**Comment by Michael-E-Rose** [comment]
@nils-herrmann could you please provide a PR? @titipata here has an untested fix.
