### ISSUE TITLE
physical & electronic publication dates can be mixed into erroneous dates

### ISSUE THREAD

**Issue by ghost** [titipata/pubmed_parser#112]
**Describe the bug**
consider [PMC 1280406](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=%271280406%27):
Published online: 2005 May 31
Published in journal: 2005 Sep

valid dates would be '2005-09' or '2005-05-31', but `pp.parse_pubmed_xml` yields '2005-09-31'

The culprit is [here](https://github.com/titipata/pubmed_parser/blob/e443d6a2f8ad754c708e6b3cd9e7535918443758/pubmed_parser/medline_parser.py#L377).

**To Reproduce**
```python
import pubmed_parser as pp
pp.parse_pubmed_xml('pmc1280406.xml')['publication_date']
'31-9-2005'
```
[pmc1280406.xml.zip](https://github.com/titipata/pubmed_parser/files/7858328/pmc1280406.xml.zip)

**Comment by titipata** [comment]
@aren-lorenson-enveda, thanks for the issue. Yes, it seems like [here](https://github.com/titipata/pubmed_parser/blob/e443d6a2f8ad754c708e6b3cd9e7535918443758/pubmed_parser/utils.py#L120-L144) is an issue. I won't have much time to fix this issue this month. Hopefully, if someone sees this issue, they can make PR to fix this!
