### ISSUE TITLE
Table parsing issues with parse_pubmed_table

### ISSUE THREAD

**Issue by octotus** [titipata/pubmed_parser#118]
Using parse_pubmed_table with PMC535341.xml and PMC535340.xml (as test papers). In both cases, parse_pubmed_table is not retrieving table info. Other modules like parse_captions / paragraphs work fine.

Any hints at what am doing wrong will be helpful. Thanks.

**Comment by raypereda-gr** [comment]
I suggest posting code on the pull request. Clearly explain what you expected, or wanted, with a test case. 

Additional nodes can be added to the parser.

**Comment by Michael-E-Rose** [comment]
Duplicate of #119
