### ISSUE TITLE
Question: Abstract with Mesh Tag

### ISSUE THREAD

**Issue by shrimonmuke0202** [titipata/pubmed_parser#122]
Hi Team,

I want to download the PubMed abstract which is annotated with MeSH tags. How can I do this?

**Comment by titipata** [comment]
Hi @shrimonmuke0202, so the simple way is to download the MEDLINE dump and then use the MEDLINE parser (`parse_medline_xml `) to parse MeSH tags. The tags are separated by `;` which you can get Mesh IDs and terms to use later on.

**Comment by titipata** [comment]
- Are the tokens of text contained in the abstract of any paper exactly matching the MeSH tags? I think MeSH tags are kinda high-level concepts of the given abstract. It may match or not match the abstract.
- From where can I download the MEDLINE dump? https://www.nlm.nih.gov/databases/download/pubmed_medline.html (there are multiple ways to download API or bulk download)
