### ISSUE TITLE
Parse language in `parse_xml_web()`

### ISSUE THREAD

**Issue by nils-herrmann** [titipata/pubmed_parser#129]
PubMed provides information on the language of a publication. Unfortunately, this information is not extracted by the parser in the function `parse_xml_web()`.

pubmed_parser should parse the language in the function [`parse_pubmed_web_tree()`](https://github.com/titipata/pubmed_parser/blob/15054992098c8e9000a3ab321894367d65f012dc/pubmed_parser/pubmed_web_parser.py#L47)

**Comment by Michael-E-Rose** [comment]
Closed with #130
