### ISSUE TITLE
Create function to caption figure caption and image link

### ISSUE THREAD

**Issue by titipata** [titipata/pubmed_parser#13]
We want to grab figure label, caption and `xlink:href` for that file so we can relate caption with images later.

**Comment by daniel-acuna** [comment]
Actually all this stuff would be amazing to have for several other projects. Not sure if the NLM format has this.

**Comment by titipata** [comment]
I wrote `lxml` to extract captions long time ago but I couldn't find it.

**Comment by daniel-acuna** [comment]
amazing
