### ISSUE TITLE
Fix Medline parser tests

### ISSUE THREAD

**Issue by nils-herrmann** [titipata/pubmed_parser#133]
**Problem**
Currently four tests are failing in the `test_medline_parser.py`:
- `test_parse_medline_xml()`
- `test_parse_medline_grant_id()`
- `test_parse_medline_mesh_terms()`
- `test_parse_medline_mesh_terms_with_sub()`

**To Reproduce**
Execute pytest: `pytest ./tests` 

**Expected behavior**
All test should pass

**To-Do**
Investigate why the test are failing, fix it and update tests

**Comment by Michael-E-Rose** [comment]
Has been done in various commits.
