### ISSUE TITLE
Fix GitHub workflows

### ISSUE THREAD

**Issue by nils-herrmann** [titipata/pubmed_parser#144]
**Describe the bug**
Every time a PR is done, GitHub conducts two checks: `test` and `docs`. Both checks fail.

**To Reproduce**
Go to [link](https://github.com/titipata/pubmed_parser/actions/runs/9226407178/job/25386097914?pr=141)

**Expected behavior**
When testing locally, I get no errors. Presumably, there is something wrong with the checks.

**Comment by Michael-E-Rose** [comment]
Failing tests could be due to outdated test data.

Failing docs could be due to different specifications of the build environment (like package versions, language, etc.)

**Comment by nils-herrmann** [comment]
The errors are caused by the workflow using an outdated incorrect branch to conduct the tests (titipata/pubmed_parser/tree/master). This also imposes a problem when testing changes in the [workflow file](https://github.com/titipata/pubmed_parser/blob/master/.github/workflows/test-and-build-docs.yml) because the workflow is using the outdates version. The changes I conducted in the workflow file should use the branch of the PR (also if it is a fork). Unfortunately I have no way to check if my changes yield the desired results.

**Comment by Michael-E-Rose** [comment]
This was fixed in 55a796c9d8fe962c44d3912487017d3973af9052.

The unexpected solution was to verify the installation before executing the tests.
