### ISSUE TITLE
It couldn't recognize the xml file I downloaded from pubmed

### ISSUE THREAD

**Issue by wildwhip** [titipata/pubmed_parser#148]
I have downloaded the xml file from "https://ftp.ncbi.nlm.nih.gov/pubmed/baseline/"
and then
```
{
	"name": "XPathEvalError",
	"message": "Error in xpath expression",
	"stack": "---------------------------------------------------------------------------
XPathEvalError                            Traceback (most recent call last)
Cell In[14], line 3
      1 import pubmed_parser as pp
      2 path_xml = pp.list_xml_path(\"...\xml\")
----> 3 pubmed_dict = pp.parse_pubmed_xml(path_xml[0]) # dictionary output
      4 print(pubmed_dict)

File ......\\pubmed_parser\\pubmed_oa_parser.py:182, in parse_pubmed_xml(path, include_path, nxml)
    179     subjects = \"\"
    181 # create affiliation dictionary
****--> 182 affil_id = tree.xpath(\".//aff[@id]/@id\")****
    183 if len(affil_id) > 0:
    184     affil_id = list(map(str, affil_id))

File src\\\\lxml\\\\etree.pyx:2342, in lxml.etree._ElementTree.xpath()

File src\\\\lxml\\\\xpath.pxi:342, in lxml.etree.XPathDocumentEvaluator.__call__()

File src\\\\lxml\\\\xpath.pxi:210, in lxml.etree._XPathEvaluatorBase._handle_result()

XPathEvalError: Error in xpath expression"
}
```

**Comment by Michael-E-Rose** [comment]
Which file specifically do you mean with `the xml file`? Also, which version are you using?

**Comment by wildwhip** [comment]
form https://ftp.ncbi.nlm.nih.gov/pubmed/baseline/
![image](https://github.com/user-attachments/assets/a50dc8d7-df3e-4e7c-be4b-8b2b0a4a6df6)

**Comment by Michael-E-Rose** [comment]
All of them, or a particular xml file? The website has multiple hundred xml files.

**Comment by titipata** [comment]
I think you might need to use `pp.parse_medline_xml` instead. The PubMed one is for PubMed Open Access corpus.

**Comment by wildwhip** [comment]
> All of them, or a particular xml file? The website has multiple hundred xml files.

yes，all of them

**Comment by wildwhip** [comment]
> I think you might need to use `pp.parse_medline_xml` instead. The PubMed one is for PubMed Open Access corpus.

where can i find this tool？
