### ISSUE TITLE
Output type in Pubmed OA is lxml.etree._ElementUnicodeResult

### ISSUE THREAD

**Issue by titipata** [titipata/pubmed_parser#24]
@daniel-acuna catched this error when we run `output = pp.parse_pubmed_xml('data/1472-6831-8-11.nxml')` and then check an output type i.e. `list(map(type, out.values()))`

Output type is 

```
[str,
 list,
 lxml.etree._ElementUnicodeResult,
 str,
 list,
 str,
 str,
 str,
 lxml.etree._ElementUnicodeResult,
 str]
```

We have to turn this type into proper string.

**Comment by daniel-acuna** [comment]
I think it is now fixed

**Comment by titipata** [comment]
Just to make sure, it is now fixed with the new commit right?

**Comment by daniel-acuna** [comment]
Yes, spark process it correctly, everything was a string

**Comment by titipata** [comment]
Nice! Close by 12c2962369fe03d56c399733226761a189c1aa3c and 5ab278acc845a8b68a2b418d80c60c4aea221348
