### ISSUE TITLE
Return PMCID when parsing Medline XML files

### ISSUE THREAD

**Issue by daniel-acuna** [titipata/pubmed_parser#25]
Some website require `PMCID` instead of `PMID`.

**Comment by titipata** [comment]
Do you want it so that it returns `pmc` as a key in output dictionary from MEDLINE parser?

**Comment by daniel-acuna** [comment]
exactly. I assume all of them have `pmc`, otherwise return null. Essentially, I want to use `pmc` to query the citations with `parse_citation_web`

**Comment by titipata** [comment]
I updated in d5869234d31beb0bcfc, can you check if that what you want?

**Comment by daniel-acuna** [comment]
it works!
