### ISSUE TITLE
Update script to download whole Pubmed OA and MEDLINE dataset

### ISSUE THREAD

**Issue by titipata** [titipata/pubmed_parser#29]
Now the script [here](https://github.com/titipata/pubmed_parser/tree/master/scripts) only download subset of the data.

**Comment by daniel-acuna** [comment]
How do you check whether you have downloaded something before?

**Comment by titipata** [comment]
Yeah, I have the checking if folder exists in `update` function. However, now I save file in the name format like `medline_DD_MM_YY.parquet`. I would like to improve the workflow where it saves log file so we can track the file.

Also, now the download and process are in the same pipeline (after running the code, it will download and process at once). I would like the ability to call function separately also.

**Comment by titipata** [comment]
This should be done in Wiki page on the repository.
