### ISSUE TITLE
Unresolved references to 'join' in pubmed_oa_parser

### ISSUE THREAD

**Issue by TariqAHassan** [titipata/pubmed_parser#31]
I believe (I could be wrong) there are three small mistakes on lines `192`, `246` and `312` of  `pubmed_oa_parser.py` in the `parse_references `, `parse_paragraph` and `parse_pubmed_caption` functions, respectively. 

The code references a function `join`, but I have been unable to locate it. Perhaps this should be corrected to reference to the string method `join` (i.e., `" ".join()`) ?

**Comment by titipata** [comment]
You are right @TariqAHassan! I had `join` function before but I removed it. Thanks for reporting. It's now fixed at 24d67610ae92419c3586e5a358e8559b662e02de

**Comment by TariqAHassan** [comment]
Don't forget about line 246 :)

**Comment by titipata** [comment]
I amended the commit  24d6761, thanks again :)
