### ISSUE TITLE
paragraphs with no references not included by parse_pubmed_paragraph

### ISSUE THREAD

**Issue by uludag** [titipata/pubmed_parser#36]
Lists returned by `parse_pubmed_paragraph` does not include paragraphs if they do not have any references. I think it would be useful if paragraphs with no references can also be returned.

**Comment by titipata** [comment]
@uludag I think that sounds great. I'm on my trip right now and I can implement it soon. Do you want to help implementing this functionality?

**Comment by uludag** [comment]
Commenting out the check `len(ref_ids) >= 1` before the append call looks safe and lets the function to return the paragraphs with no references. This was a change I made for my tests, however my work with using the library was brief and I have not had a broad understanding of **pubmed_parser**.

**Comment by titipata** [comment]
@uludag, thanks! I'm working on it and will let you know when I change it directly on the repository.

**Comment by titipata** [comment]
I actually did change it but forgot to close the issue. I'll close the issue for now :)
