### ISSUE TITLE
Problem with parsing MEDLINE baseline 2017 xml files

### ISSUE THREAD

**Issue by chengkun-wu** [titipata/pubmed_parser#39]
Hi, I found the code works well with MEDLINE 2016 baseline. However, when I tried to apply it to the MEDLINE 2017 baseline, only PMIDs were parsed, other fields are blank. Anyone aware of that? Thanks!

Chengkun

**Comment by titipata** [comment]
Oh, can you give an example or link to file in `ftp`? I can check that for you. Maybe they update new structure of the file and I wasn't aware of that.

**Comment by chengkun-wu** [comment]
Example file: medline17n1024.xml

Example output:

```
>>> out = pp.parse_medline_xml('medline17n1024.xml')
>>> print out
[{'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': None, 'author': None, 'other_id': None, 'pmid': '24381829', 'journal': None, 'delet
e': True}, {'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': None, 'author': None, 'other_id': None, 'pmid': '26841407', 'journal': No
ne, 'delete': True}, {'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': None, 'author': None, 'other_id': None, 'pmid': '27257533', 'jo
urnal': None, 'delete': True}, {'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': None, 'author': None, 'other_id': None, 'pmid': '2739
2785', 'journal': None, 'delete': True}, {'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': None, 'author': None, 'other_id': None, 'pm
id': '27533762', 'journal': None, 'delete': True}, {'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': None, 'author': None, 'other_id':
 None, 'pmid': '27642677', 'journal': None, 'delete': True}, {'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': None, 'author': None, '
other_id': None, 'pmid': '27653842', 'journal': None, 'delete': True}, {'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': None, 'author
': None, 'other_id': None, 'pmid': '27870391', 'journal': None, 'delete': True}, {'mesh_terms': None, 'abstract': None, 'affiliation': None, 'year': None, 'keywords': None, 'title': Non
e, 'author': None, 'other_id': None, 'pmid': '27873125', 'journal': None, 'delete': True}]
```

**Comment by titipata** [comment]
Ah I see, so these are papers that got updated so you might have two xmls for the same paper. Therefore, delete means that you should delete the record of the old paper because it got updated.

So basically when delete field is `True`, we’ll return all None: https://github.com/titipata/pubmed_parser/blob/master/pubmed_parser/medline_parser.py#L359-L379. So don’t worry about those PMIDs!

**Comment by chengkun-wu** [comment]
Thanks for the hint! 
Still a little bit confused, as if I tried with the true baseline file medline17n0116.xml.gz (I attached it in this reply), 

`>>> import pubmed_parser as pp
>>> out = pp.parse_medline_xml('medline17n0116.xml.gz')
>>> print out`

it returns nothing. 

I downloaded the file from ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/, is that the correct place? Or did I make some other mistakes?

Thanks again!

[medline17n0116.xml.gz](https://github.com/titipata/pubmed_parser/files/809916/medline17n0116.xml.gz)

**Comment by titipata** [comment]
@chengkun-wu that's weird, I did the same thing

```python
parsed = pp.parse_medline_xml('medline17n0116.xml.gz')
df_parsed = pd.DataFrame(parsed)
```

and I got 30000 parsed articles from attached file (tested with Python 3.5, 3.6). Do you give the right path to `xml.gz` file?

**Comment by chengkun-wu** [comment]
I'm using Python 2.7. Can you please test it as well? The weird thing is that it works well for the medline16 xml files.

**Comment by chengkun-wu** [comment]
Hi @titipata , I downloaded the latest version of pubmed_parser, and now it works! Thanks for all the replies! BTW, is there any support for parsing the PMC Open-Acsess full-text xml??

**Comment by titipata** [comment]
@chengkun-wu, that's great! Seems like you have old version that doesn't check the correct tree.

For PMC Open-Access, the `parse_pubmed_paragraph` is the closest one that we have. You can parse the paragraph and section from full-text of Pubmed OA using `parse_pubmed_paragraph(path, all_paragraph=True)`, this will give you structured format from XML file. Please feel free to open the issue of your use case so that I can add the functionality.
