### ISSUE TITLE
Apply unidecode to the parsed string

### ISSUE THREAD

**Issue by titipata** [titipata/pubmed_parser#4]

**Comment by daniel-acuna** [comment]
What do you mean with this issue? The strings generated are already unicode. Please give more details :)

**Comment by titipata** [comment]
Oh, some of them are not read properly like tilde over the character. I don't know whether we should apply unidecode to the string

**Comment by daniel-acuna** [comment]
I think we should keep those strings. I might be a problem with the pubmed files rather than the parser. Using unidecode would make you lose some important characters - like ñ in Acuña ;) 

Should close this issue then?

**Comment by titipata** [comment]
Yeah totally agree, close the issue
