### ISSUE TITLE
python-2.7 import error: No module named 'request'

### ISSUE THREAD

**Issue by uludag** [titipata/pubmed_parser#48]
In my environment python-2.7 is not able to find the module _urllib.request_ required by _pubmed_web_parser.py_.

If I replace the _urllib_ import statement as suggested in [this discussion](https://stackoverflow.com/questions/31601238/python-2-7-10-error-from-urllib-request-import-urlopen-no-module-named-request) then python2 is able to find the _request_ module:

```python
try:
    from urllib.request import urlopen
except ImportError:
    from urllib2 import urlopen
```
_urlopen_ is used by the function _parse_outgoing_citation_web_ in the same file. For all http requests from this file _requests_ library is used except the request made from the function _parse_outgoing_citation_web_. It could be possible to use the _requests_ library here as well? to avoid the import.

--mahmut

**Comment by titipata** [comment]
Thanks so much for the issue @uludag! I fixed it already. Let me know if you see others issue. I mostly develop in Python 3 these days and might overlook few issues with Python 2.

**Comment by digitalstem** [comment]
import urllib.request, json
ImportError: No module named request


i m getting the following error plz.. help

**Comment by baijuct** [comment]
You cannot have request in Python 2, you need to have Python 3 or above.

**Comment by JanisSharma** [comment]
To install requests module on Debian/Ubuntu for Python2:

$ sudo apt-get install python-requests

And for Python3 the command is:

$ sudo apt-get install python3-requests

Full Source At [Here](https://icetutor.com/question/importerror-no-module-named-requests/)
