### ISSUE TITLE
feature request: MeSH IDs

### ISSUE THREAD

**Issue by pseudomonas** [titipata/pubmed_parser#50]
It'd be useful to be able to get MeSH IDs as well as heading names. I've used the following quick-and-dirty change to `medline_parser.py` but there's probably a more elegant way.

`mesh_terms_list = [m.find('DescriptorName').attrib.get('UI','') + ":" + m.find('DescriptorName').text for m in mesh.getchildren()]`

**Comment by titipata** [comment]
That's a great idea! Would you like to do pull-request or should I add it later this week?

**Comment by pseudomonas** [comment]
I'll leave it to you; my fix is not backwards-compatible if that matters to
you...

**Comment by titipata** [comment]
Definitely, I'll notify you when it's done :)

**Comment by titipata** [comment]
@pseudomonas, this is actually done. I forgot to close the issue :)
