### ISSUE TITLE
Parse Pubmed OA Paragraph

### ISSUE THREAD

**Issue by soupstandstop** [titipata/pubmed_parser#59]
Hi,
Why did I enter: `pp.parse_pubmed_paragraph('data/6605965a.nxml', all_paragraph=False)`
the return is empty list?

**Comment by soupstandstop** [comment]
I supposed that it will return the section text of this PMC?

**Comment by titipata** [comment]
@soupstandstop, in the particular file, there is no text content in the given PMC. You can check the file inside `data` folder.

**Comment by soupstandstop** [comment]
Yes, but in the case of the file that there have text in PMC, I still have the empty list.

**Comment by soupstandstop** [comment]
ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/00/00/
The nxml file in PMC5640403.tar.gz
You can check there this file, the return is still empty?

**Comment by soupstandstop** [comment]
I make the Pull request, if have any problem please tell me, thanks!

**Comment by MananVyas24** [comment]
Observed the same behavior for all NXML (even from the data samples) for the function pp.parse_pubmed_paragraph. Debugging, as we speak, to know why this is happening and will keep you updated.

**Comment by titipata** [comment]
Thanks so much @MananVyas24. Let me know if you figure out where the error comes from. I do not have much time to debug but will check out the PR as soon as possible!

**Comment by titipata** [comment]
@soupstandstop I checked and b2ccfe7 and a769744 fix this issue. Let me know if you have any problem parsing the paragraph text using a recent version of `pubmed_parser`.
