### ISSUE TITLE
`stringify_affiliation` function return excess whitespace

### ISSUE THREAD

**Issue by titipata** [titipata/pubmed_parser#6]
According to function `stringify_affiliation`, we return `' '.join(filter(None, parts))`. So, it solve problem if we have multiple children node but for some case it returns excess space for example `University ,  Turku ,  Finland`. We should return more reliable string format.

**Comment by daniel-acuna** [comment]
I think this only happens when we have punctuations. Maybe we can write a regular expression to make the replacement?

**Comment by titipata** [comment]
Yeah, we can write regular expression to solve it. But I don't know whether regular expression will take much more time for whole parser or not. What do you think?

**Comment by daniel-acuna** [comment]
Nah, I don't think it will add much. The parser is already pretty far - half a second on my computer. We could start from something like this http://stackoverflow.com/questions/8717190/eliminate-leading-trailing-spaces-around-punctuation-marks?

**Comment by titipata** [comment]
Oh nice, I like it. It's not mandatory but should we add it?

**Comment by daniel-acuna** [comment]
I think so

**Comment by titipata** [comment]
@daniel-acuna I tested our recent Pubmed Parser on several PubMed file. I think it's good so I will close the issue.
