### ISSUE TITLE
medline xml equivalent for "parse_pubmed_references"?

### ISSUE THREAD

**Issue by huminpurin** [titipata/pubmed_parser#64]
I get `"AttributeError: 'NoneType' object has no attribute 'find'"` for using `parse_pubmed_references` on xml files of MEDLINE/PubMed Data (https://www.nlm.nih.gov/databases/download/pubmed_medline.html)

`parse_medline_xml` can parse xmls but not getting refference. I checked the xml files and im sure the reference data is in there. Is there any way to get something like "parse_medline_references"?

**Comment by titipata** [comment]
Hi @huminpurin, can you point to tue sample of XML file that you're obtaining from? I will have more time next week to fix the library.

**Comment by huminpurin** [comment]
I got the file from the official database of national library of medicine: ftp://ftp.ncbi.nlm.nih.gov/pubmed/updatefiles/

**Comment by titipata** [comment]
@huminpurin, I see now. So, we currently do not have the implementation for parsing MEDLINE references yet. I am checking out now if I can get the references from MEDLINE. However, implementing such function (`parse_medline_xml`) would be great to have for the library!

**Comment by titipata** [comment]
@huminpurin, I actually do not see the reference data from MEDLINE dataset. If you can point to the specific file name that has references data for me, I can try to implement it for you.

**Comment by huminpurin** [comment]
@titipata It would be great if you could implement (parse_medline_xml) function, afterall all files on nlm database are medline xml. 
To answer your question, there is a tag as `<ReferenceList>` in the xml files which lists the reference list of a paper. Heres some example codes from the actual file: 
`      <ReferenceList>
        <Reference>
          <Citation>Proc Natl Acad Sci U S A. 2012 Apr 10;109(15):5850-5</Citation>
          <ArticleIdList>
            <ArticleId IdType="pubmed">22454498</ArticleId>
          </ArticleIdList>
        </Reference>
        <Reference>
          <Citation>ACS Synth Biol. 2017 Jul 21;6(7):1296-1304</Citation>
          <ArticleIdList>
            <ArticleId IdType="pubmed">28274123</ArticleId>
          </ArticleIdList>
        </Reference>
        ......`

**Comment by titipata** [comment]
@huminpurin, ah nice, thanks a lot! I did not notice it exists before. It seems like the reference are not available for all of the XML. However, I will take a look and update with you soon.

**Comment by huminpurin** [comment]
@titipata Oh I see where the problem is. No all the files contain reference list in following database
[ftp://ftp.ncbi.nlm.nih.gov/pubmed/updatefiles/](url)
Only some of the files contain reference list. I just checked the last one `pubmed19n1117.xml.gz` . Maybe the old data don't have reference list.

**Comment by titipata** [comment]
Fixed in #69.
