### ISSUE TITLE
pip3 install wget

### ISSUE THREAD

**Issue by fayyasfayz** [titipata/pubmed_parser#65]
pip3 install wget Every time i run this command....it shows "command not found".....plz help to fix this error.

**Comment by bluenex** [comment]
Which step are you doing? Why do you need to install `wget` via `pip`?

From the error, it indicates that you don't have `pip3` installed properly. Which Python version do you use? Please try running these commands and send us the output so that we have more information.

```sh
python --version
```

```sh
which python
```

**Comment by titipata** [comment]
Hi @fayyasfayz, I will close this issue. Let me know if you can resolve the problem you have.
