### ISSUE TITLE
JOSS paper text

### ISSUE THREAD

**Issue by tleonardi** [titipata/pubmed_parser#77]
Hi,
I've noticed that citation of `mesbah2018smartpub` is not rendered properly in the compiled [PDF](https://github.com/openjournals/joss-papers/blob/joss.01979/joss.01979/10.21105.joss.01979.pdf).

I've also made some syntax and style changes, feel free to merge to reject them (950eed22c449d7384b231150a0bffccaf33c8436).

**Comment by titipata** [comment]
@tleonardi I've made the changes in [`paper.md`](https://github.com/titipata/pubmed_parser/blob/master/paper/paper.md) accordingly in 901791d3f78a78edd1af1d04244810d6495c16a8 and f88d422818caf2f7dd94b0ac7c9eb9bfcbdcd699. Now, the citation should be rendered correctly [here](http://res.cloudinary.com/hju22ue2k/image/upload/v1579558758/zyykxe1gbioadtmnmodk.pdf). I was missing one citation in the bib file.  

@daniel-acuna Can you help check my writing in [`CONTRIBUTING.md`](https://github.com/titipata/pubmed_parser/blob/master/CONTRIBUTING.md) and [`README.md`](https://github.com/titipata/pubmed_parser#contributions)? Also, can you help check my writing additional use-cases of Pubmed Parser in [`paper.md`](https://github.com/titipata/pubmed_parser/blob/master/paper/paper.md)?

-  **Note** here to render PDF in [Whedon](https://whedon.theoj.org/) with `https://github.com/titipata/pubmed_parser` and `master` branch.

**Comment by tleonardi** [comment]
Perfect!
