### ISSUE TITLE
Contributing guidelines are missing

### ISSUE THREAD

**Issue by tleonardi** [titipata/pubmed_parser#79]
Hi,
JOSS requires the repository to have clear Community guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support.
As a starting point you could use this CC0 template [here](https://gist.github.com/peterdesmet/e90a1b0dc17af6c12daf6e8b2f044e7c)

**Comment by titipata** [comment]
@tleonardi Thank you so much. I will update the contribution guideline accordingly. Hopefully, this will be done by mid of this week. I will tag you once it's done.

**Comment by titipata** [comment]
@tleonardi We now add Contributing Guidelines [here](https://github.com/titipata/pubmed_parser/blob/master/CONTRIBUTING.md). We also link it on the `README.md`.

Let me know if we need more documentation improvement. Thanks again for your suggestions.

**Comment by tleonardi** [comment]
Great, I'll check it off on JOSS!
