### ISSUE TITLE
Missing details in API docs

### ISSUE THREAD

**Issue by tleonardi** [titipata/pubmed_parser#82]
Hi,
I've noticed some functions miss the sphinx documentation: 
parse_pubmed_paragraph(): the parameter all_paragraph is not documented
table_to_df(): parameters and return value not documented
parse_pubmed_web_tree(): parameters and return value not documented
extract_citations():  parameters and return value not documented
extract_pmc():  parameters and return value not documented

**Comment by titipata** [comment]
I've fixed this issue in 7d4ae40. I will further update the documentation and point to this issue later on!
