### ISSUE TITLE
Parsing abstract section

### ISSUE THREAD

**Issue by titipata** [titipata/pubmed_parser#9]
There can be one or more section in single abstract. For example, we can have `BACKGROUND`, `METHOD`, `RESULT` or just `Abstract` and `RESULT` in single abstract etc. We want to add some tagger when we parse these abstracts in case people want to analyze only few parts of abstract.

I'm still not sure which format should we return in this case.

**Comment by daniel-acuna** [comment]
Can you give me a PMID that has this problem? I would just capture the entire abstract into one text field.

**Comment by titipata** [comment]
Here are few PMID that exist in Open Access subset: 18612225, 22992293, 22494660, 24884587, 20513246, 18612228, 24991066, 18350110, 18350111, 18350115, 22363803, 20635453, 22992294, 23068712, 18350125, 24641586, 24991070, 18350135, 18350136, 23505588

**Comment by titipata** [comment]
Here is an example of XML from PMID22992293, see http://www.ncbi.nlm.nih.gov/pubmed/22992293. It would be nice if we can get text for each section with corresponding title. However, we want to remove xml tag inside the text e.g. `<sub>2</sub>`, `<italic>in vivo</italic>`

```
      <abstract>
        <sec>
          <title>Background</title>
          <p>Our ongoing research has revealed that total saponins extracted from the medicinal herb Radix Astragali (AST) exhibits significant growth-inhibitory and proapoptotic effects in human cancer cells. In the present study, the potential of AST in controlling angiogenesis was further investigated with elaboration of the underlying molecular mechanism in human colon cancer cell and tumor xenograft.</p>
        </sec>
        <sec>
          <title>Results</title>
          <p>AST decreased the protein level of VEGF and bFGF in HCT 116 colon cancer cells in a time- and dose-dependent manner. Among the Akt/mTOR signal transduction molecules being examined, AST caused PTEN upregulation, reduction in Akt phosphorylation and subsequent activation of mTOR. AST also suppressed the induction of HIF-1&#945; and VEGF under CoCl<sub>2</sub>-mimicked hypoxia. These effects were intensified by combined treatment of AST with the mTOR inhibitor rapamycin. Despite this, our data also indicate that AST could attenuate cobalt chloride-evoked COX-2 activation, while such effect on COX-2 and its downstream target VEGF was intensified when indomethacin was concurrently treated. The anti-carcinogenic action of AST was further illustrated in HCT 116 xenografted athymic nude mice. AST significantly suppressed tumor growth and reduced serum VEGF level <italic>in vivo</italic>. In the tumor tissues excised from AST-treated animals, protein level of p-Akt, p-mTOR, VEGF, VEGFR1 and VEGFR2 was down-regulated. Immunohistochemistry has also revealed that AST effectively reduced the level of COX-2 in tumor sections when compared with that in untreated control.</p>
        </sec>
        <sec>
          <title>Conclusion</title>
          <p>Taken together, these findings suggest that AST exerts anti-carcinogenic activity in colon cancer cells through modulation of mTOR signaling and downregulation of COX-2, which together reduce VEGF level in tumor cells that could potentially suppress angiogenesis.</p>
        </sec>
      </abstract>
```

**Comment by daniel-acuna** [comment]
thanks. I'll take a look

**Comment by daniel-acuna** [comment]
Pubmed parser is returning all the text inside this kind of abstract, which
I think is correct. How do you want to format the title sections? If you
want to preserve sections, would that mean that you would be willing to
preserve it as an XML?

**Comment by titipata** [comment]
I would like to get more refine result from abstract section as an option like `{'abstract': '...', 'method': '...', ...}` (probably not in this format tho). It might be helpful for someone who want to grab only particular chunk of abstract.

**Comment by titipata** [comment]
I will close this issue for now.
